apiVersion: v1
kind: Service
metadata:
  name: phone-api-loadbalancer
  labels:
    app: phone-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: phone-api